# Generated by Django 5.1.15 on 2026-08-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='event_starts_at_idx',
            old_name='events_even_starts__b01102_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='event_language_idx',
            old_name='events_even_languag_67ce95_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='event_location_idx',
            old_name='events_even_locatio_0ae1f4_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of seats. Leave blank for unlimited capacity.', null=True),
        ),
    ]
